---
    - name: Deploy python microservice
      hosts: application
      become: true
      
      pre_tasks:
        - name: apt update
          apt:
            update_cache: 
        - name: Install python3-pip
          apt:
            name: python3-pip
            state: latest
      roles:
        - role: geerlingguy.docker
      post_tasks:
        - name: Install docker-py python package
          pip:
            name: docker-py

      tasks:
        - name: Re-create a redis container
          community.general.docker_container:
            name: python-microservice
            image: "1k3tv1nay/python-microservice:{{COMMITHASH}}"
            command: python3 server.py
            state: present
            ports:
              - 5000:8080