---
    - name: Deploy python microservice
      hosts: application
      become: true
      
      pre_tasks:
        - name: apt update
          apt:
            update_cache: true

      tasks:
        - name: Re-create a redis container
          community.general.docker_container:
            name: python-microservice
            image: "1k3tv1nay/python-microservice:{{COMMIT_HASH}}"
            command: python3 server.py
            state: present
            ports:
              - 5000:8080