---
    - name: Deploy python microservice
      hosts: application
      become: true
      
      pre_tasks:
        - name: apt update
          apt:
            update_cache: 
        - name: Install python3-pip
          apt:
            name: python3-pip
            state: latest
        - name: Install docker python package
          pip:
            name: docker
            state: absent
        - name: Install docker-py python package
          pip:
            name: docker-py
            state: present
      roles:
        - role: geerlingguy.docker

      tasks:
        - name: run python server in docker
          docker:
            name: python-microservice
            image: "1k3tv1nay/python-microservice:{{COMMITHASH}}"
            command: "python3 server.py"
            state: reloaded
            pull: always
            ports:
              - 5000:8080