---
    - name: Deploy python microservice
      hosts: application
      become: true
      
      pre_tasks:
        - name: apt update
          apt:
            update_cache: true
        - name: install ansible galaxy roles required
          shell:
            cmd: "ansible-galaxy install geerlingguy.docker"

        - name: install ansible galaxy roles required
          shell:
              cmd: "ansible-galaxy collection install community.general"
    
      roles:
        - role: geerlingguy.docker